# Site settings
title: Tim Patzelt
description: Machine Learning Engineer - Personal Website
url: "https://tpatzelt.github.io"
baseurl: ""

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - wrangler.toml
  - .bundle

# Custom variables
author:
  name: Tim Patzelt
  email: tim.p@posteo.de
  github: tpatzelt
  linkedin: tim-patzelt-3248a1168
  typing_text: Machine Learning Engineer
